apiVersion: apps/v1
kind: Deployment
metadata:
  name: showcase-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showcase-backend
  template:
    metadata:
      labels:
        app: showcase-backend
    spec:
      containers:
        - name: showcase-backend
          image: raccoonsteam/backend:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: kyma-showcase-secret
                  key: REDIS_URL
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kyma-showcase-secret
                  key: REDIS_PASSWORD
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: kyma-showcase-secret
                  key: PORT

