apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: raccoonsteam/backend:events
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: REDIS_URL
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: REDIS_PASSWORD
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: PORT
            - name: EVENT_TYPE
              value: "sap.kyma.custom.commerce.order.created.v1"
            - name: EVENT_URL
              value: "http://eventing-event-publisher-proxy.kyma-system/publish"

