apiVersion: v1
kind: Service
metadata:
  name: showcase-backend-service
  labels:
    app: showcase-backend
spec:
  selector:
    app: showcase-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081